# Generated by Django 5.2.8 on 2025-11-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('contactName', models.CharField(max_length=100)),
                ('contactTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('shipperID', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('reportsTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='trader.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('requiredDate', models.DateField()),
                ('shippedDate', models.DateField(blank=True, null=True)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trader.customer')),
                ('employeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trader.employee')),
                ('shipperID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trader.shipper')),
            ],
            options={
                'ordering': ['-orderDate'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('quantityPerUnit', models.CharField(max_length=100)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discontinued', models.BooleanField(default=False)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trader.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(db_index=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='trader.order')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='trader.product')),
            ],
            options={
                'verbose_name_plural': 'Order Details',
                'unique_together': {('orderID', 'productID')},
            },
        ),
    ]
